spring:
  datasource:
    url: jdbc:mysql://10.20.253.242:3306/fangniuke?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: rzw
    password: "0703"
    # password: 123
  mvc:
    servlet:
      multipart:
        max-file-size: 10MB        # ???????????10MB
        max-request-size: 100MB    # ?????????100MB
    static-path-pattern: /static/**
  tomcat:
    max-http-post-size: -1

  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 20MB

server:
  port: 80

  web:
    resources:
      static-locations: classpath:/static/

