spring:
  datasource:
    url: jdbc:mysql://10.20.253.242:3306/fangniuke?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: rzw
    password: "0703"
    # password: 123

server :
  port : 80